# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: articletemplates																							#Pflichtfeld
version: '1.0.1'																								#Pflichtfeld
author: Falko Müller
supportpage: https://github.com/iceman-fx/articletemplates

page:
    title: 'translate:a1826_title'
    perm: articletemplates[]
    icon: rex-icon fa-files-o
    subpages:
        default: { title: 'translate:a1826_default' }
        cat: { title: 'translate:a1826_cat' }

        help: { title: 'translate:a1826_help', icon: rex-icon fa-info-circle, itemclass: pull-right }
        config: { title: 'translate:a1826_config', icon: rex-icon fa-wrench, itemclass: pull-right }

requires:
    redaxo: '^5.15.0'